services:
  mysql:
    image: mysql:8.0
    container_name: mysql_delivery
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    container_name: backend_delivery
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mysql
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db_data:
