services:
  mysql:
    image: mysql:8.0
    container_name: mysql_delivery
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: delivery_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    container_name: backend_delivery
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: delivery_db
      DB_DIALECT: mysql
      JWT_SECRET: segredoseguro
    depends_on:
      - mysql
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db_data:
